/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AttendTokenRouteImport } from './routes/attend.$token'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as BookSessionRouteImport } from './routes/book.session'
import { Route as BookSlotRouteImport } from './routes/book.slot'
import { Route as BookVerifyRouteImport } from './routes/book.verify'
import { Route as BookedTokenRouteImport } from './routes/booked.$token'
import { Route as CancelTokenRouteImport } from './routes/cancel.$token'
import { Route as NdaTokenRouteImport } from './routes/nda.$token'
import { Route as RescheduleTokenRouteImport } from './routes/reschedule.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendTokenRoute = AttendTokenRouteImport.update({
  id: '/attend/$token',
  path: '/attend/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSessionRoute = BookSessionRouteImport.update({
  id: '/book/session',
  path: '/book/session',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlotRoute = BookSlotRouteImport.update({
  id: '/book/slot',
  path: '/book/slot',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVerifyRoute = BookVerifyRouteImport.update({
  id: '/book/verify',
  path: '/book/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BookedTokenRoute = BookedTokenRouteImport.update({
  id: '/booked/$token',
  path: '/booked/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelTokenRoute = CancelTokenRouteImport.update({
  id: '/cancel/$token',
  path: '/cancel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NdaTokenRoute = NdaTokenRouteImport.update({
  id: '/nda/$token',
  path: '/nda/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RescheduleTokenRoute = RescheduleTokenRouteImport.update({
  id: '/reschedule/$token',
  path: '/reschedule/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/attend/$token': typeof AttendTokenRoute
  '/book/session': typeof BookSessionRoute
  '/book/slot': typeof BookSlotRoute
  '/book/verify': typeof BookVerifyRoute
  '/booked/$token': typeof BookedTokenRoute
  '/cancel/$token': typeof CancelTokenRoute
  '/nda/$token': typeof NdaTokenRoute
  '/reschedule/$token': typeof RescheduleTokenRoute
  '/book/': typeof BookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/attend/$token': typeof AttendTokenRoute
  '/book/session': typeof BookSessionRoute
  '/book/slot': typeof BookSlotRoute
  '/book/verify': typeof BookVerifyRoute
  '/booked/$token': typeof BookedTokenRoute
  '/cancel/$token': typeof CancelTokenRoute
  '/nda/$token': typeof NdaTokenRoute
  '/reschedule/$token': typeof RescheduleTokenRoute
  '/book': typeof BookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/attend/$token': typeof AttendTokenRoute
  '/book/session': typeof BookSessionRoute
  '/book/slot': typeof BookSlotRoute
  '/book/verify': typeof BookVerifyRoute
  '/booked/$token': typeof BookedTokenRoute
  '/cancel/$token': typeof CancelTokenRoute
  '/nda/$token': typeof NdaTokenRoute
  '/reschedule/$token': typeof RescheduleTokenRoute
  '/book/': typeof BookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/attend/$token'
    | '/book/session'
    | '/book/slot'
    | '/book/verify'
    | '/booked/$token'
    | '/cancel/$token'
    | '/nda/$token'
    | '/reschedule/$token'
    | '/book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/attend/$token'
    | '/book/session'
    | '/book/slot'
    | '/book/verify'
    | '/booked/$token'
    | '/cancel/$token'
    | '/nda/$token'
    | '/reschedule/$token'
    | '/book'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/attend/$token'
    | '/book/session'
    | '/book/slot'
    | '/book/verify'
    | '/booked/$token'
    | '/cancel/$token'
    | '/nda/$token'
    | '/reschedule/$token'
    | '/book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  AttendTokenRoute: typeof AttendTokenRoute
  BookSessionRoute: typeof BookSessionRoute
  BookSlotRoute: typeof BookSlotRoute
  BookVerifyRoute: typeof BookVerifyRoute
  BookedTokenRoute: typeof BookedTokenRoute
  CancelTokenRoute: typeof CancelTokenRoute
  NdaTokenRoute: typeof NdaTokenRoute
  RescheduleTokenRoute: typeof RescheduleTokenRoute
  BookIndexRoute: typeof BookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attend/$token': {
      id: '/attend/$token'
      path: '/attend/$token'
      fullPath: '/attend/$token'
      preLoaderRoute: typeof AttendTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/session': {
      id: '/book/session'
      path: '/book/session'
      fullPath: '/book/session'
      preLoaderRoute: typeof BookSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/slot': {
      id: '/book/slot'
      path: '/book/slot'
      fullPath: '/book/slot'
      preLoaderRoute: typeof BookSlotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/verify': {
      id: '/book/verify'
      path: '/book/verify'
      fullPath: '/book/verify'
      preLoaderRoute: typeof BookVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booked/$token': {
      id: '/booked/$token'
      path: '/booked/$token'
      fullPath: '/booked/$token'
      preLoaderRoute: typeof BookedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel/$token': {
      id: '/cancel/$token'
      path: '/cancel/$token'
      fullPath: '/cancel/$token'
      preLoaderRoute: typeof CancelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nda/$token': {
      id: '/nda/$token'
      path: '/nda/$token'
      fullPath: '/nda/$token'
      preLoaderRoute: typeof NdaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reschedule/$token': {
      id: '/reschedule/$token'
      path: '/reschedule/$token'
      fullPath: '/reschedule/$token'
      preLoaderRoute: typeof RescheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  AttendTokenRoute: AttendTokenRoute,
  BookSessionRoute: BookSessionRoute,
  BookSlotRoute: BookSlotRoute,
  BookVerifyRoute: BookVerifyRoute,
  BookedTokenRoute: BookedTokenRoute,
  CancelTokenRoute: CancelTokenRoute,
  NdaTokenRoute: NdaTokenRoute,
  RescheduleTokenRoute: RescheduleTokenRoute,
  BookIndexRoute: BookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
