/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminOutboxRouteImport } from './routes/admin.outbox'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AttendTokenRouteImport } from './routes/attend.$token'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as BookSessionRouteImport } from './routes/book.session'
import { Route as BookSlotRouteImport } from './routes/book.slot'
import { Route as BookVerifyRouteImport } from './routes/book.verify'
import { Route as BookedTokenRouteImport } from './routes/booked.$token'
import { Route as CancelTokenRouteImport } from './routes/cancel.$token'
import { Route as NdaTokenRouteImport } from './routes/nda.$token'
import { Route as RescheduleTokenRouteImport } from './routes/reschedule.$token'
import { Route as ApiPublicHooksAutomationsRouteImport } from './routes/api/public/hooks/automations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOutboxRoute = AdminOutboxRouteImport.update({
  id: '/outbox',
  path: '/outbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AttendTokenRoute = AttendTokenRouteImport.update({
  id: '/attend/$token',
  path: '/attend/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSessionRoute = BookSessionRouteImport.update({
  id: '/book/session',
  path: '/book/session',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlotRoute = BookSlotRouteImport.update({
  id: '/book/slot',
  path: '/book/slot',
  getParentRoute: () => rootRouteImport,
} as any)
const BookVerifyRoute = BookVerifyRouteImport.update({
  id: '/book/verify',
  path: '/book/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BookedTokenRoute = BookedTokenRouteImport.update({
  id: '/booked/$token',
  path: '/booked/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelTokenRoute = CancelTokenRouteImport.update({
  id: '/cancel/$token',
  path: '/cancel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NdaTokenRoute = NdaTokenRouteImport.update({
  id: '/nda/$token',
  path: '/nda/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RescheduleTokenRoute = RescheduleTokenRouteImport.update({
  id: '/reschedule/$token',
  path: '/reschedule/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutomationsRoute =
  ApiPublicHooksAutomationsRouteImport.update({
    id: '/api/public/hooks/automations',
    path: '/api/public/hooks/automations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/outbox': typeof AdminOutboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/attend/$token': typeof AttendTokenRoute
  '/book/session': typeof BookSessionRoute
  '/book/slot': typeof BookSlotRoute
  '/book/verify': typeof BookVerifyRoute
  '/booked/$token': typeof BookedTokenRoute
  '/cancel/$token': typeof CancelTokenRoute
  '/nda/$token': typeof NdaTokenRoute
  '/reschedule/$token': typeof RescheduleTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/book/': typeof BookIndexRoute
  '/api/public/hooks/automations': typeof ApiPublicHooksAutomationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/outbox': typeof AdminOutboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/attend/$token': typeof AttendTokenRoute
  '/book/session': typeof BookSessionRoute
  '/book/slot': typeof BookSlotRoute
  '/book/verify': typeof BookVerifyRoute
  '/booked/$token': typeof BookedTokenRoute
  '/cancel/$token': typeof CancelTokenRoute
  '/nda/$token': typeof NdaTokenRoute
  '/reschedule/$token': typeof RescheduleTokenRoute
  '/admin': typeof AdminIndexRoute
  '/book': typeof BookIndexRoute
  '/api/public/hooks/automations': typeof ApiPublicHooksAutomationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/outbox': typeof AdminOutboxRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/attend/$token': typeof AttendTokenRoute
  '/book/session': typeof BookSessionRoute
  '/book/slot': typeof BookSlotRoute
  '/book/verify': typeof BookVerifyRoute
  '/booked/$token': typeof BookedTokenRoute
  '/cancel/$token': typeof CancelTokenRoute
  '/nda/$token': typeof NdaTokenRoute
  '/reschedule/$token': typeof RescheduleTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/book/': typeof BookIndexRoute
  '/api/public/hooks/automations': typeof ApiPublicHooksAutomationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/privacy'
    | '/reset-password'
    | '/admin/bookings'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/outbox'
    | '/admin/settings'
    | '/attend/$token'
    | '/book/session'
    | '/book/slot'
    | '/book/verify'
    | '/booked/$token'
    | '/cancel/$token'
    | '/nda/$token'
    | '/reschedule/$token'
    | '/admin/'
    | '/book/'
    | '/api/public/hooks/automations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/reset-password'
    | '/admin/bookings'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/outbox'
    | '/admin/settings'
    | '/attend/$token'
    | '/book/session'
    | '/book/slot'
    | '/book/verify'
    | '/booked/$token'
    | '/cancel/$token'
    | '/nda/$token'
    | '/reschedule/$token'
    | '/admin'
    | '/book'
    | '/api/public/hooks/automations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/privacy'
    | '/reset-password'
    | '/admin/bookings'
    | '/admin/inbox'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/outbox'
    | '/admin/settings'
    | '/attend/$token'
    | '/book/session'
    | '/book/slot'
    | '/book/verify'
    | '/booked/$token'
    | '/cancel/$token'
    | '/nda/$token'
    | '/reschedule/$token'
    | '/admin/'
    | '/book/'
    | '/api/public/hooks/automations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AttendTokenRoute: typeof AttendTokenRoute
  BookSessionRoute: typeof BookSessionRoute
  BookSlotRoute: typeof BookSlotRoute
  BookVerifyRoute: typeof BookVerifyRoute
  BookedTokenRoute: typeof BookedTokenRoute
  CancelTokenRoute: typeof CancelTokenRoute
  NdaTokenRoute: typeof NdaTokenRoute
  RescheduleTokenRoute: typeof RescheduleTokenRoute
  BookIndexRoute: typeof BookIndexRoute
  ApiPublicHooksAutomationsRoute: typeof ApiPublicHooksAutomationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/outbox': {
      id: '/admin/outbox'
      path: '/outbox'
      fullPath: '/admin/outbox'
      preLoaderRoute: typeof AdminOutboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/attend/$token': {
      id: '/attend/$token'
      path: '/attend/$token'
      fullPath: '/attend/$token'
      preLoaderRoute: typeof AttendTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/session': {
      id: '/book/session'
      path: '/book/session'
      fullPath: '/book/session'
      preLoaderRoute: typeof BookSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/slot': {
      id: '/book/slot'
      path: '/book/slot'
      fullPath: '/book/slot'
      preLoaderRoute: typeof BookSlotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/verify': {
      id: '/book/verify'
      path: '/book/verify'
      fullPath: '/book/verify'
      preLoaderRoute: typeof BookVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booked/$token': {
      id: '/booked/$token'
      path: '/booked/$token'
      fullPath: '/booked/$token'
      preLoaderRoute: typeof BookedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel/$token': {
      id: '/cancel/$token'
      path: '/cancel/$token'
      fullPath: '/cancel/$token'
      preLoaderRoute: typeof CancelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nda/$token': {
      id: '/nda/$token'
      path: '/nda/$token'
      fullPath: '/nda/$token'
      preLoaderRoute: typeof NdaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reschedule/$token': {
      id: '/reschedule/$token'
      path: '/reschedule/$token'
      fullPath: '/reschedule/$token'
      preLoaderRoute: typeof RescheduleTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automations': {
      id: '/api/public/hooks/automations'
      path: '/api/public/hooks/automations'
      fullPath: '/api/public/hooks/automations'
      preLoaderRoute: typeof ApiPublicHooksAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOutboxRoute: typeof AdminOutboxRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOutboxRoute: AdminOutboxRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AttendTokenRoute: AttendTokenRoute,
  BookSessionRoute: BookSessionRoute,
  BookSlotRoute: BookSlotRoute,
  BookVerifyRoute: BookVerifyRoute,
  BookedTokenRoute: BookedTokenRoute,
  CancelTokenRoute: CancelTokenRoute,
  NdaTokenRoute: NdaTokenRoute,
  RescheduleTokenRoute: RescheduleTokenRoute,
  BookIndexRoute: BookIndexRoute,
  ApiPublicHooksAutomationsRoute: ApiPublicHooksAutomationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
